name: Debian

on:
  push:
    tags: "*"

jobs:
  package:
    runs-on: ubuntu-18.04
    container: heliumsystems/builder-erlang:2

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # fetch all branch and tag history
          fetch-depth: 0

      - name: Name Release
        id: get-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

      - name: Build tar
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: rebar3 as prod tar

      - name: Upload tar artifact
        uses: actions/upload-artifact@v2
        with:
          name: blockchain-node.${{ steps.get-tag.outputs.tag }}.tar.gz
          path: _build/prod/rel/blockchain_node/blockchain_node*.tar.gz

      - name: remove tarball # so it doesn't get packaged in debian
        run: rm _build/prod/rel/blockchain_node/blockchain_node*.tar.gz

      - name: Build deb
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        uses: bpicode/github-action-fpm@master
        with:
          fpm_args: '_build/prod/rel/=/var/helium'
          fpm_opts: |
            -n blockchain-node \
            -v ${{ steps.get-tag.outputs.tag }}
            -s dir \
            -t deb \
            --depends libssl1.1 \
            --depends libsodium23 \
            --deb-systemd deb/blockchain-node.service \
            --deb-no-default-config-files

      - name: Upload deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: blockchain-node.${{ steps.get-tag.outputs.tag }}.deb
          path: blockchain_node*.deb

      # Automatically uploads debs in current directory
      - name: Upload packagecloud
        uses: lpenz/ghaction-packagecloud@master
        with:
          repository: helium/internal
          env:
            PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
